version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: sudo npm install
          command: sudo npm install -g npm@latest
      - run:
          app-dir: ~/project/server
          name: npm run test
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test