version: '2.1'
orbs:
  node: circleci/node@5.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@02.2.1
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest --prefix ~/project/server
      - run: npm run test --prefix ~/project/server

workflows:
  test_my_app:
    jobs:
      - test
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          dockerfile: Dockerfile